### ISSUE TITLE
Get test steps is failing

### ISSUE THREAD

**Issue by iosu1998** [jesper-raemaekers/python-polarion#100]
Hello, I'm using getTestSteps method inside the workitem class and I got the following issue:

```
custom_fields = service.getCustomFieldTypes(self.uri)
if any(field.id == 'testSteps' for field in custom_fields):
      service_test = self._polarion.getService('TestManagement')
      self._polarion_test_steps = service_test.getTestSteps(self.uri)
```

https://github.com/jesper-raemaekers/python-polarion/blob/028e085211c42fdf2231ea37a68800ed6722d5d9/polarion/workitem.py#L101

This line is throwing the following exception:
zeep.exceptions.XMLParseError: Unexpected element '{http://ws.polarion.com/TrackerWebService-types}enumId', expected '{http://ws.polarion.com/TrackerWebService-types}id

In my case, I could solve it replacing that code with:

```
custom_field = service.getCustomFieldType(self.uri, "Test Steps")
if custom_field.id == 'Test Steps':
      service_test = self._polarion.getService('TestManagement')
      self._polarion_test_steps = service_test.getTestSteps(self.uri)
```

I'm using:
- python 3.9
- zeep==4.1.0
- urllib3==1.26.9
- requests==2.27.1

Thanks

**Comment by jesper-raemaekers** [comment]
Your fix looks good, better than the code that was there. I will take it along with the branch to add some more test step support.
Thanks!
