### ISSUE TITLE
workitem.setCustomField() for Text multi-line

### ISSUE THREAD

**Issue by elettorhamid** [jesper-raemaekers/python-polarion#111]
Hello,
  I need help in setting the Custom Field for Text multi-line of a work item.. I have no problems setting a normal string but not the Text multi-line.

If this is supported please help me understand how to set .. if not supported I am not sure how to implement it myself.
simple code I am using is:
workitem = project.getWorkitem(PolarionID)
workitem.setCustomField('Verif_Criteria', "my text")

if I change the setting in admin to simple string, the same code works.. if I set it to multi-line it gives an error.
using project.searchWorkitem(PolarionID, field_list=['customFields.Verif_Criteria'] ) I can see that the structure is this:
'customFields': {
        'Custom': [
            {
                'key': 'Verif_Criteria',
                'value': {
                    'type': 'text/plain',
                    'content': 'Hello',
                    'contentLossy': False
                }
            }
        ]
    },

I have modified the custom_fields.py to match the structure but still not working.. I have done the following:
self.customFields.Custom.append(self._polarion.CustomType(key=key, value={'type': 'text/plain', 'content': value, 'contentLossy': False}))
 which if I print it is as follows matching the above: {
    'key': 'Verif_Criteria',
    'value': {
        'type': 'text/plain',
        'content': 'my text',
        'contentLossy': False
    }
}

Please let me know soon... Thanks a lot.

**Comment by jesper-raemaekers** [comment]
Hi,

Have a look in this issue: https://github.com/jesper-raemaekers/python-polarion/issues/106#issuecomment-1475364406
I think this answers the same question.

Let me know if this doesn't work for you.

**Comment by elettorhamid** [comment]
That was brilliant!.. works perfectly!.. thanks a lot..  for some reason I didn't find that comment myself before :( .. 
Thanks for the support.

**Comment by elettorhamid** [comment]
Hi Jesper,
  Looks like I am having another issue on the same custom field. 
If the custom field is blank --> I am able to write to it no problem.
If the custom field has already been written to and try to rewrite again exactly the same way (and even the same string) I get this:

workitem.setCustomField(key='Verif_Criteria', value= client.TextType(type='text/plain', content=VerificationCriteria, contentLossy=False))

  File "C:\Users\hamid\Anaconda3\lib\site-packages\polarion\base\custom_fields.py", line 36, in setCustomField
    custom_field.value = eval(value)

TypeError: eval() arg 1 must be a string, bytes or code object

Please let me know if any idea why!.. Thanks a lot.

**Comment by jesper-raemaekers** [comment]
Hi,

Can you post more info?
I can rerun this code over and over and it works. Even when I edit the value in polarion first.
```
wi.setCustomField(key='string_field', value=pol.TextType(type='text/plain', content='something', contentLossy=False))
```

**Comment by elettorhamid** [comment]
This is basically my fullcode:

 ***********************
          from polarion.polarion import Polarion
          client = Polarion(---, ----, ---)
          project = client.getProject("TEST_01")
          workitem = project.getWorkitem("TEST_01A-84")
          VerificationCriteria = "My test"
          workitem.setCustomField(key='Verif_Criteria', value= client.TextType(type='text/plain', content=VerificationCriteria, contentLossy=False))
          print("Done!")
***********************

So I run it after clearing manually the custom field.

Output after first run:

***********************
       Done!
***********************

Output after second run, without changing anything, just rerunning:

***********************
  File "C:\Users\me\drive\Documents\mydoc\Python\quickTestPolarion.py", line 12, in <module>
    workitem.setCustomField(key='Verif_Criteria', value= client.TextType(type='text/plain', content=VerificationCriteria, contentLossy=False))

  File "C:\Users\me\Anaconda3\lib\site-packages\polarion\base\custom_fields.py", line 36, in setCustomField
    custom_field.value = eval(value)

TypeError: eval() arg 1 must be a string, bytes or code object
***********************

Could it be some settings in my Polarion project?  so I have edited the custom_fields.py to print the "value" passed to the eval()..this is the output:

***********************
This is my value: {
    'type': 'text/plain',
    'content': 'My test',
    'contentLossy': False
} 
***********************

so it is directly the dictionary and the format looks ok?.. 

Now when I clear the custom field and it runs ok.. the code goes where the first arrow is pointing , when there is already something in the custom field, the code goes where the second arrow is pointing below:

<img width="531" alt="image" src="https://user-images.githubusercontent.com/128898214/231547571-97e12c33-a8d0-4764-bccb-a5239aa2d1bd.png">


Hope this is useful enough to debug it.. thanks a lot.

**Comment by elettorhamid** [comment]
Just to add to that, forcing the code as below to have customFields = None, makes it work fine and I can rerun and edit without problems.. but not sure this is the right approach and what implication would have on other parts of the code. 

<img width="508" alt="image" src="https://user-images.githubusercontent.com/128898214/231548950-0bd777ef-1a31-461a-9abb-b60f5fab1a76.png">

**Comment by jesper-raemaekers** [comment]
This is good info. 
How many custom fields does this work item type have?
I wondering what the value of custom field is at this line: https://github.com/jesper-raemaekers/python-polarion/blob/main/polarion/base/custom_fields.py#L31 where there already was a value in there that you cleared.

**Comment by elettorhamid** [comment]
So this work item has only one custom field.

This is the value of custom field at the line you asked:

**************************
This is my customField at line 31:  {
    'key': 'Verif_Criteria',
    'value': {
        'type': 'text/plain',
        'content': 'My test and something else',
        'contentLossy': False
    }
}
************************************
