### ISSUE TITLE
Possible bug for failure case

### ISSUE THREAD

**Issue by miltkall** [jesper-raemaekers/python-polarion#112]
Hello there,

thank you for you amazing lib! 

I am having the following xUnit generated from the Robot Framework

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Vcan Testsuite" tests="2" errors="0" failures="1" skipped="0" time="6.826" timestamp="2023-03-31T15:52:36.508000">
    <testcase classname="Vcan Testsuite" name="tbx-19497 vcan0: Test sending and receiving vcan0 messages" time="2.457">
        <failure message="'  vcan0  123   [4]  DE AD BE EE' does not contain 'vcan0  123   [4]  DE AD BE EF'" type="AssertionError"/>
    </testcase>
    <testcase classname="Vcan Testsuite" name="tbx-19498 vcan1: Test sending and receiving vcan1 messages" time="2.499">
    </testcase>
    <properties>
        <property name="Documentation" value="Hostname: prometheus Date: 20230331"/>
    </properties>
</testsuite>
```
I am using the `Config.from_dict` and the `Importer.from_xml(config) `  in order to parse the XML  and import in Polarion. If the failure line gets deleted, everything works fine. Any suggestions, where the problem could be? 

Many thanks 👍🏿

**Comment by jesper-raemaekers** [comment]
Hi,

Can you try locally changing the following line: https://github.com/jesper-raemaekers/python-polarion/blob/main/polarion/xml.py#L155
To this:

```
if elem.text is not None:
    text.append(elem.text)
```

I think the XML parser requires a message inside a failure element. This if makes that optional. Let me know if this works for you.

Jesper

**Comment by miltkall** [comment]
Yes sir that was the problem. 

Do you want me to make a pull request or you will take care of it? 

Many thanks!
