### ISSUE TITLE
Set Outline Number / Move Workitem to specific Document Location

### ISSUE THREAD

**Issue by CloudyAtSES** [jesper-raemaekers/python-polarion#119]
Is there a way to set the Outline Number of a Workitem or moving the Workitem to a specific Document Heading? If not, could you please implement such a feature?

**Comment by jesper-raemaekers** [comment]
Hi,

Yes it can, but it is a bit annoying. You can use moveToDocument which accepts a parent work item. In polarion documents, all headers are also workitems.
So you need to get the correct chapter header as workitem and then use moveToDocument with that as parent.

Let me know if you would need an example.

Jesper
