### ISSUE TITLE
getWorkitems() throws "Workitem not retrieved from Polarion" exception for missing work items

### ISSUE THREAD

**Issue by apper13** [jesper-raemaekers/python-polarion#137]
I try to get a list of all work items the following way:
```
    document = project.getDocument(polarion_document)
    work_items = document.getWorkitems()
```
If there are work items in a document which do not exist, the call to `getWorkitems()` raises the exception "Workitem not retrieved from Polarion". I would either expect just ignoring non-existing work items or just returning the number. Comparable problems arise when trying to get linked work items (`getLinkedItemWithRoles()`) which no longer exist.

**Comment by jesper-raemaekers** [comment]
It seems that when deleting from the user interface, workitems get nicely removed from documents. When using the API, this is not the case.
I just added a try/except to silence it.

**Comment by apper13** [comment]
> It seems that when deleting from the user interface, workitems get nicely removed from documents. When using the API, this is not the case. I just added a try/except to silence it.

I am not a Polarion expert, but I think it not only happens when deleting via API, but also when a work item is referenced in more than one document. If you delete it from one document it will not be deleted from another. You can even insert work item referenced from project A into a page from project B.
Thank you for adding try/except!
