### ISSUE TITLE
Getting linked items fails with deleted items

### ISSUE THREAD

**Issue by mrtnnwmn** [jesper-raemaekers/python-polarion#138]
I'm using getLinkedItemWithRoles() and on a particular work item I get the error below:
```
    470 if self.linkedWorkItemsDerived is not None:
    471     for linked_item in self.linkedWorkItemsDerived.LinkedWorkItem:
--> 472         linked_items.append((linked_item.role.id, Workitem(self._polarion, self._project, uri=linked_item.workItemURI)))
    473 return linked_items

AttributeError: 'NoneType' object has no attribute 'id'
```
Looking at the work item in Polarion it seems that there are links to two items that have been deleted, so I assume the method is failing when it attempts to add the deleted items to the linked work items list. Could you add a check for work item validity?

**Comment by jesper-raemaekers** [comment]
I was not able to reproduce it, but I added a check that should solve this exception.

**Comment by alexandertoepfer** [comment]
I have had the same issue, it happens because links in polarion do not guarantee the workitem exists, I would advise to check in your system for such dangling links, otherwise you can always hack "try: ... except: continue" around the list append

**Comment by jesper-raemaekers** [comment]
I think this happens when items are deleted using the API. it seems that the GUI of Polarion also cleans up all references, but this may not be the case for the API. Did @z3r0k3ys experience this issue with the latest package version?

**Comment by z3r0k3ys** [comment]
I will be able to provide an answer by Monday, because unfortunately I'm using a forked version with the try except block to avoid this issue, but I can guarantee the problem is not the package, it's rather that those references are allowed to exist in the first place, which should be addressed by polarion

**Comment by z3r0k3ys** [comment]
You could add a flag for safety to turn missing items into just a warning, but from my point of view this can be closed
