### ISSUE TITLE
Link role doesn't set opposite name

### ISSUE THREAD

**Issue by elettorhamid** [jesper-raemaekers/python-polarion#139]
I have a new problem if you can support please.

The issue I have is that through python script I do set a requirement item link using role “is derived from” and I would assume that the parent requirement should have “is derived by”

When done through Polarion interface it works but not through script. 
The line code I use in python is the following:

requirementItem.addLinkedItem(project.getWorkitem(Parent_ID), “is derived from”)

Thanks.

**Comment by bigblondewolf** [comment]
I support this, I have a discussion thread on the topic (#130), but it got no attention.

**Comment by elettorhamid** [comment]
Good to know I am not the only one.. I will have a look and if I find a solution will let you know. Thanks.

**Comment by elettorhamid** [comment]
Ok.. I had some time to look into it now .. my mistake was using the name of the role "is derived from".. instead I should have used the id "derived_from".
I wish it would through an error if you just use a simple string which is not part of the given enumeration! ..

Anyway problem solved.

**Comment by vicnet** [comment]
Thanks for your comment.
I will test your solution with id, but it seems coherent.
Should be add in docstring :)
