### ISSUE TITLE
New test runs but traceability to existing test cases or requirements

### ISSUE THREAD

**Issue by TristanFAURE** [jesper-raemaekers/python-polarion#140]
Hello
Thank you for the library

I use the junit import feature that is very convenient.

I have an open question.

I have functional requirements and functional test cases
My Tests are technical and it is ok to have new test cases with the format "className.methodName", but I would like in my test to add information to create traceability to my functional test cases or requirements for instance:

Polarion server
+ REQ 001
+ REQ 002

Java code
+ class 1
  + method1
+ class 2
  + method 1

Do you think with the junit importer I can import a new test run with new tests cases and create a traceability link to REQ 001 or REQ 002 ?

After import I would expect this kind of traceability:
REQ 001 -> Test Case class1.method1

Thank you in advance !

**Comment by LionnelC** [comment]
JUnit xml format doesn't contain natively this data.
It contains only test case => test result. So need to extend the import to another format.

**Comment by TristanFAURE** [comment]
Thanks for the comment !
It seems that test suites and test cases : https://github.com/testmoapp/junitxml#properties
I don't really see java frameworks that generate them but it seems pytest yes.

Maybe we could provide a feature where some traceability links could be created thanks to these properties ? It would be the responsibility of the developers and testers to add this metadata to the test xml result file

**Comment by TristanFAURE** [comment]
for information X Ray does the same way
https://docs.getxray.app/display/XRAY/Import+Execution+Results#ImportExecutionResults-JUnitXMLoutputformat
