### ISSUE TITLE
Authentication already required at earlier point

### ISSUE THREAD

**Issue by ChrisOpitz** [jesper-raemaekers/python-polarion#151]
Login is done too late, therefore, due to missing authentication at that point, the following functions fail:

Here the login page is returned, therefore the services list can't be obtained:
```python
    def _getServices(self):
        """
        Parse the list of services available in the overview
        """
        service_overview = requests.get(self.url, verify=self.verify_certificate)
``` 

Creating the Client...
```python
    def _createSession(self):
        """
        Starts a session with the specified user/password
        """
        if 'Session' in self.services:
            self.history = HistoryPlugin()
            self.services['Session']['client'] = Client(
                self.services['Session']['url'] + '?wsdl', plugins=[self.history], transport=self._getTransport())
``` 

... also results in trying to create a WSDL Document based on returned XML content (which is not the case - the login page content is returned here as well)
```python
document = self._get_xml_document(location)
``` 

Using:
Polarion® ALM™ 2304
Build: 3.23.4.20230416-1128-2304-b065e427

**Comment by jesper-raemaekers** [comment]
For the first issue you could use static_service_list=True in the Polarion constructor as a workaround. But Indeed, the user should be logged in when trying to get these pages.
