### ISSUE TITLE
Error occurred when using a for loop to retrieve data from polarion

### ISSUE THREAD

**Issue by JiangChangda** [jesper-raemaekers/python-polarion#161]
hello,

I don't know if the amount of data accessed is too large, resulting in the following problems:
_'Connection aborted.', RemoteDisconnected('Remote end closed connection without response'）_

I would greatly appreciate it if you could solve this problem.
JCD

**Comment by JiangChangda** [comment]
14:21:08  Traceback (most recent call last):
14:21:08    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\connectionpool.py", line 791, in 
14:21:08  urlopen
14:21:08      response = self._make_request(
14:21:09                 ^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\connectionpool.py", line 537, in 
14:21:09  _make_request
14:21:09      response = conn.getresponse()
14:21:09                 ^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\connection.py", line 461, in 
14:21:09  getresponse
14:21:09      httplib_response = super().getresponse()
14:21:09                         ^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "http\client.py", line 1378, in getresponse
14:21:09    File "http\client.py", line 318, in begin
14:21:09    File "http\client.py", line 287, in _read_status
14:21:09  http.client.RemoteDisconnected: Remote end closed connection without response
14:21:09  
14:21:09  During handling of the above exception, another exception occurred:
14:21:09  
14:21:09  Traceback (most recent call last):
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\requests\adapters.py", line 486, in send
14:21:09      resp = conn.urlopen(
14:21:09             ^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\connectionpool.py", line 845, in 
14:21:09  urlopen
14:21:09      retries = retries.increment(
14:21:09                ^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
14:21:09      raise reraise(type(error), error, _stacktrace)
14:21:09            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
14:21:09      raise value.with_traceback(tb)
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\connectionpool.py", line 791, in 
14:21:09  urlopen
14:21:09      response = self._make_request(
14:21:09                 ^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\connectionpool.py", line 537, in 
14:21:09  _make_request
14:21:09      response = conn.getresponse()
14:21:09                 ^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\urllib3\connection.py", line 461, in 
14:21:09  getresponse
14:21:09      httplib_response = super().getresponse()
14:21:09                         ^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "http\client.py", line 1378, in getresponse
14:21:09    File "http\client.py", line 318, in begin
14:21:09    File "http\client.py", line 287, in _read_status
14:21:09  urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
14:21:09  
14:21:09  During handling of the above exception, another exception occurred:
14:21:09  
14:21:09  Traceback (most recent call last):
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\polarion\workitem.py", line 45, in __init__
14:21:09      self._polarion_item = service.getWorkItemByUri(self._uri)
14:21:09                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\zeep\proxy.py", line 46, in __call__
14:21:09      return self._proxy._binding.send(
14:21:09             ^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\zeep\wsdl\bindings\soap.py", line 127, in send
14:21:09      response = client.transport.post_xml(options["address"], envelope, http_headers)
14:21:09                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\zeep\transports.py", line 108, in post_xml
14:21:09      return self.post(address, message, headers)
14:21:09             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\zeep\transports.py", line 74, in post
14:21:09      response = self.session.post(
14:21:09                 ^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\requests\sessions.py", line 637, in post
14:21:09      return self.request("POST", url, data=data, json=json, **kwargs)
14:21:09             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\requests\sessions.py", line 589, in request
14:21:09      resp = self.send(prep, **send_kwargs)
14:21:09             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\requests\sessions.py", line 703, in send
14:21:09      r = adapter.send(request, **kwargs)
14:21:09          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\requests\adapters.py", line 501, in send
14:21:09      raise ConnectionError(err, request=request)
14:21:09  requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
14:21:09  
14:21:09  During handling of the above exception, another exception occurred:
14:21:09  
14:21:09  Traceback (most recent call last):
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk/TestFramework/TestAutomation/Utilities/JenkinsScript/TraceTest.py", line 65, in <module>
14:21:09      ExecTraceTest.executeTraceTest(TVGC.ComParameter, TVGC.ExecuteTraceTestParameter)
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\TestExecution\TraceTest\ExecTraceTest.py", line 54, in executeTraceTest
14:21:09      retVal = project.ExecuteTraceTest(par)
14:21:09               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\AccessPolarion\AccessPolarion.py", line 2340, in ExecuteTraceTest
14:21:09      traceTestPasrser = self.TestRun_TraceTestPasrser(self.project, filterTraceTest.traceTestCases)
14:21:09                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\AccessPolarion\AccessPolarion.py", line 971, in __init__
14:21:09      linkTestCases = traceTestCase.getLinkedItemWithRoles()
14:21:09                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\polarion\workitem.py", line 479, in 
14:21:09  getLinkedItemWithRoles
14:21:09      linked_items.append((linked_item.role.id, Workitem(self._polarion, self._project, uri=linked_item.workItemURI)))
14:21:09                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14:21:09    File "C:\jenkins_slave\workspace\PSoC4\TestExecution\TraceTest\AutoPDL\trunk\TestFramework\TestAutomation\Utilities\Python3.x\Lib\site-packages\polarion\workitem.py", line 48, in __init__
14:21:09      raise Exception(
14:21:09  Exception: Cannot find workitem None in project SW_PSOC4_AUTO_PDL

**Comment by WH-Yoshi** [comment]
Hi,
Could you provide more information?

This could occur for several reason which can be from server to network to client sided.
But the more obvious problem for me would be a connection timeout.
If you can't find a workaround, try changing your code.

**Comment by JiangChangda** [comment]
Process:
TestCase(More than 200 ergodic)->Get linked TestCase(About 30 or so)->Search for TestRun based on linked TestCase ID(There are about 5 of them)->Obtain the results of TestCase in the latest TestRun

Description:
During this process, the following functions trigger the above issues frequently:
getLinkedItemWithRoles()
searchTestRuns()
getWorkitem()

One of the Traceback logs is shown below:
[Traceback_log.txt](https://github.com/jesper-raemaekers/python-polarion/files/14899590/Traceback_log.txt)
