### ISSUE TITLE
In LiveDoc, getChildren(workitem) does not return elements in order

### ISSUE THREAD

**Issue by micrenda** [jesper-raemaekers/python-polarion#166]
In LiveDoc, when using `document.getChildren(workitem)`, the items do not have the same order as the LiveDoc. 

A possible workaround is to sort, after retrieval, according to the field `workitem.outline_number`, but a native solution would be better.

Thank you for the excellent library, which is saving lives!

**Comment by superlou** [comment]
I'm also interested in this. Sorting isn't trivial, since you need to remember to do [natural sorting](https://en.wikipedia.org/wiki/Natural_sort_order).

Edit: I'm sorting the returned items using the [natsort](https://natsort.readthedocs.io/en/stable/) package:

```py
workitems = doc.getWorkitems()
workitems = natsorted(workitems, key=lambda x: x.outlineNumber)
```
