### ISSUE TITLE
Update record

### ISSUE THREAD

**Issue by iosu1998** [jesper-raemaekers/python-polarion#169]
Hello,

I'm trying to update the record results and I've just realized that, even for each step, a "retest comment" label is added even for each step.

Debbuging, I've reached the conclusion that it's because of the Record Save method, which is using the ExecuteTest wsdl and it's used in both setStepResult and setResult.

Whenever I update the results I update both. That's why  just having the save in the setResult will suit me.

Also, would be interesting to use the wsdl method UpdateTestRecord or UpdateTestRecordAtIndex.

The comparison between this two methods and the previous one, according to the web service, is the following:

- **Execute Test**: Executes Test Cases given by the Test Records within a specified Test Run. This method differs from others within this web service because it can execute multiple Test Cases in a single call. It can also create a defect if a Test Case fails. (If configured to do so on the Polarion server.) It replaces having to call multiple web services like addTestRecord(...) or updateTestRecord(...) and the manual creation of a defect. Test parameters in the supplied Test Records override any parameters contained within the original planned test records and the Test Run itself. If a required parameter is supplied with an empty value, the Method will fail. It is not necessary to fill in all the parameters, only those that do not have a value set in the Test Run or planned Test Case, or those that should be changed. 
- **UpdateTestRecordAtIndex**: Updates or removes the Test Record at a given index in the Test Run. Test parameters should not be entered in the supplied Test Record because they are ignored by this method.

So, with the second one, results could be updated in the way the user wants to, I think that could be interesting to apply it, in order to modify already uploaded record.

Also, I didn't see any manual way to delete records from Polarion manually.

I don't know which is the best way to do this. In my case just the comment and the result fields are interesting to be changed, but I guess I should implement also the other ones and I don't know which is the best way to do it. In my case I'm copying the record, doing the same as it's done in the Save method to fill the new item and afterwards modifying the comment and the result to fit the new ones.

I can try doing something and then modify my changes and let it properly.

Thank you.

**Comment by nunobrum** [comment]
I implemented in my clone repository a dedicated class for managing test records. 
It doesn't solve everything but it's more efficient and easy to use. 
I tried to pull-request it back to origin, but it's tricky to maintain backward compatibility.
