### ISSUE TITLE
verify_certificate=False does not works

### ISSUE THREAD

**Issue by micrenda** [jesper-raemaekers/python-polarion#174]
When the Polarion site uses self-signed certificate, the verify_certificate flag does not work:

`requests.exceptions.SSLError: HTTPSConnectionPool(host='xxxxxxxxxxx', port=443): Max retries exceeded with url: /polarion/ws/services/SessionWebService?wsdl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))`

The issue is that WSDL is fetched when the Client is instanced, and we did not have time to set the client to ignore SSL errors.

To fix the issue, please take a look at the attached [pull-request](https://github.com/jesper-raemaekers/python-polarion/pull/175).

PS. After using verify_certificate=False, you may want to use: `requests.packages.urllib3.disable_warnings()` to hide warning messages.

**Comment by okh555** [comment]
Hello, In my case, I faced same issue, but I resolved by install certifi, pyOpenSSL.

pip install pyOpenSSL
pip install certifi

Why don't you try above install.

**Comment by You69Man** [comment]
After updating from V1.3.0 to V1.4.0 my project breaks with get the same error message as described here. 
I would very much appreciate the fix done by @micrenda!
