### ISSUE TITLE
exception when logging into Polarion server

### ISSUE THREAD

**Issue by ergorion** [jesper-raemaekers/python-polarion#22]
Hi!

I'm using python-polarion (0.1.14) with python 3.8 under Win10 to access two different Polarion servers. It seems that one of them changed configuration in the last couple of weeks, because suddenly logging in creates an AttributeError exception in polarion.py:_updateServices.
I could not find any other workaround, than adding a try/except clause:
```
                try:
                    self.services[service]['client'].service.addComment._proxy._binding.get(
                    'addComment').input.body.type._element[1].nillable = True
                except AttributeError:
                    pass
```

Maybe this indicates that adding comments was disabled on the server?
Would be nice if this missing service would not keep you from logging into the server at all.
Thanx,
Axel

**Comment by jesper-raemaekers** [comment]
Could you post the exception?
Also could you post a section from the wsdl interface specification from that server that creates this exception?
You can do that by navigating to the http://<polarion_url>/polarion/ws/services/TrackerWebService?wsdl and navigating to this section:
```
<wsdl:operation name="addComment">
<wsdl:documentation>
Adds a comment to a Work Item, Document, Test Run or as a reply to an existing comment. @param parentObjectUri The URI of the parent object (not null). @param title The title of the new comment or {@code null}. @param content The content of the new comment or {@code null}. @throws java.rmi.RemoteException if the title is not null in a Document or reply comment, or if the parent URI is of an object that does not support comments. @since 3.10.2
</wsdl:documentation>
<wsdl:input message="impl:addCommentRequest" name="addCommentRequest"/>
<wsdl:output message="impl:addCommentResponse" name="addCommentResponse"/>
</wsdl:operation>
```
The line of code in question handles the option of title being null as specified here:
```
@param title The title of the new comment or {@code null}
```
I'm very interested to see if that is now different in that polarion server.

**Comment by ergorion** [comment]
Here is the exception:
AttributeError: Service has no operation 'addComment'

And looking at the wsdl confirms this: while one server (where login works flawlessly) does have the <wsdl:operation name="addComment"> entry between the two operations <wsdl:operation name="addCategory"> and <wsdl:operation name="addCommentToActivity">, the server in question does not have this entry addComment.

Maybe this option was switched off, because (I know that) the server will shortly be migrated to another environment.

Hope this answers your question?
Axel

**Comment by jesper-raemaekers** [comment]
I've create V0.1.15 with an update for this. I could not properly test that it does not crash so can you verify that this solves your crash?

**Comment by ergorion** [comment]
0.1.15 seems to fix this (unless some caching interferes with my testing, but I double checked the modification timestamps...). Looks good, thanx!
