### ISSUE TITLE
any plans to support the planning web service?

### ISSUE THREAD

**Issue by ergorion** [jesper-raemaekers/python-polarion#25]
We are working a lot with polarion plans, and it seems that they are not available through the work item api. Rather, a new web service seems to be required (I guess it is this one here: https://almdemo.polarion.com/polarion/sdk/doc/javadoc/com/polarion/alm/ws/client/planning/PlanningWebService.html)

I'd love to be able to add/remove work items to plans via python-polarion...

**Comment by jesper-raemaekers** [comment]
Well lucky you, i had some time to spare and made a basic implementation for this. Have a look at the docs: https://python-polarion.readthedocs.io/en/latest/plan.html

So only the basics are there, but just let me know what you're missing. I'm closing this one, but feel free to open a new one once you have something new :)
