### ISSUE TITLE
Accessing additional workitem properties

### ISSUE THREAD

**Issue by krishtej23** [jesper-raemaekers/python-polarion#26]
Hi,
I am trying to access `getExternalLinkingModules()` from [https://almdemo.polarion.com/polarion/sdk/doc/javadoc/com/polarion/alm/tracker/model/IWorkItem.html#getExternalLinkingModules()](url) as
```
docList = projectObj.getWorkitem("XYZ-1234").getExternalLinkingModules()
```
but I get an error saying `getExternalLinkingModules()` is not there. How can I access this function?
Thanks in advance.

**Comment by jesper-raemaekers** [comment]
I created an example in a branch. It´s not ready yet to integrate as the remove method is not working yet. Hopefully this example helps.

**Comment by jesper-raemaekers** [comment]
Ah I misread. In this case the answer is a no. This function is not available via the wsdl api.

**Comment by krishtej23** [comment]
So there is no way of accessing that function?

**Comment by jesper-raemaekers** [comment]
No. you can view the list of available functions of the API on http://<your domain>/polarion/ws/services . I find that there is nothing to find references, or a comparable function to getExternalLinkingModules. 
Maybe it's doable by creating a query to look for this, but i haven't tried.

**Comment by krishtej23** [comment]
Ok. I couldn't directly replicate this function but atleast I could get an SQL  query to get ONLY the referenced items in a document and then get the location of them. This way I exported them to an excel and could search in there.

**Comment by jesper-raemaekers** [comment]
Could you share the query so i can test with it?

**Comment by krishtej23** [comment]
Query:
```
sampleQuery = "SQL:(SELECT item.* FROM POLARION.WORKITEM item, POLARION.MODULE doc, POLARION.PROJECT proj WHERE proj.C_ID = **project_ID** AND doc.FK_PROJECT = proj.C_PK AND doc.C_ID = **document_id** AND EXISTS (SELECT rel1.* FROM POLARION.REL_MODULE_WORKITEM rel1 WHERE rel1.FK_URI_MODULE = doc.C_URI AND rel1.FK_URI_WORKITEM = item.C_URI)) AND NOT document.id:\"**Space_name**/**document_id**\" AND type:**workitem_type**"
```
calling this via `Tracker` services 
```
list_Of_WI = services.queryWorkItems(ref_wi_query, "outlineNumber", "customFields.source")
```
This gives ONLY the list of work items in a particular document that are referenced. I then looped through all the documents in a space and exported the list of work items to excel. There I searched for a work item and it gives me a list of documents that work item is referenced in.
