### ISSUE TITLE
unable to connect to Polarion Gen 2

### ISSUE THREAD

**Issue by dave2711** [jesper-raemaekers/python-polarion#45]
Hello Team,

was trying to connect to Polarion gen 2 link using python 3.8.2. but keep getting 

requests.exceptions.SSLError: HTTPSConnectionPool(host='polariong2.com', port=443): Max retries exceeded with url: /polarion/ws/services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

**Comment by Futsch1** [comment]
You seem to use a self-signed SSL certificate. You can skip the certificate validation by setting the parameter skip_cert_verification in the Polarion object constructor.

`polarion = polarion.Polarion(url, username, password, skip_cert_verification=True)`

**Comment by dave2711** [comment]
@Futsch1 I tired your solution but it says below.
Traceback (most recent call last):
    client = polarion.Polarion(,skip_cert_verification=True)
TypeError: __init__() got an unexpected keyword argument 'skip_cert_verification'

**Comment by Futsch1** [comment]
Have a look at the discussion here: https://github.com/jesper-raemaekers/python-polarion/issues/44

**Comment by dave2711** [comment]
I copied latest code in local and worked fine. Hope the pip installation issue will be resolved son So I can fetch latest using pip.

**Comment by jesper-raemaekers** [comment]
This is now available using pip from version 0.3.0.
