### ISSUE TITLE
How to create a new testcase?

### ISSUE THREAD

**Issue by sgranjoux** [jesper-raemaekers/python-polarion#48]
Hi,

I'm able to create a testrun and testcases but I haven't found how to add those testcases in the testrun. There is only functions to check or get existing testcase. I have tried to create a new Record object but I don't have anything for the polarion_record argument as it's a new one. Is there a way to do that?

**Comment by jesper-raemaekers** [comment]
Hi @sgranjoux ,

Have a look at the commit I made for this: https://github.com/jesper-raemaekers/python-polarion/commit/b88dd7bf44eb42052868ce6977ffaf7e61596320
This should help you. It will also be released in the next release.

Jesper

**Comment by sgranjoux** [comment]
Hi Jesper,

Thank you for your fast reply, it fulfill my needs. In fact, I have found something a bit similar using executeTest instead of addTestRecordToTestRun because I have several testcases to add in the testrun.
