### ISSUE TITLE
workitem not properly created when retrieved from plan

### ISSUE THREAD

**Issue by ergorion** [jesper-raemaekers/python-polarion#51]
When you retrieve a plan from polarion with 
plan = project.getPlan('plan_id') 
retrieve all work items from the plan with 
listOfWIs = plan.getWorkitemsInPlan()
and then print the first (or any) element out like:
print (listOfWIs[0])
you will see an output like:
None: <title of work item>

In other words, workitem._id is not properly set. The remaining fields seem to be set ok.

**Comment by jesper-raemaekers** [comment]
Thanks for reporting.
I did reproduce it and made a fix for it which will be released with the next release.
