### ISSUE TITLE
searchWorkitem with 'customFields' request doesn't work

### ISSUE THREAD

**Issue by nickdante8** [jesper-raemaekers/python-polarion#53]
Hello,

I try to get polarion workitem information with searchWrokitem method. I need just a couple of fields to retrieve to make it faster and it seems that for 'customFields' it doesn't work. For this field I get None even if a lot of workitems does have this kind of field in Polarion.

When I use getWorkitem I get 'customFields' as well, but I have other 3000 workitems and it takes a lot of time to do so, that's why I need to use searchWrokitem instead.

Used command:
workitems_design_element = project.searchWorkitem('type:sw_architecture_element', 'id', ['id', 'customFields'])

Could someone help me with this? Is there a problem with python-polarion library?

Thank you!

**Comment by jesper-raemaekers** [comment]
Hi,

You are very close, you specify the custom field(s) like so:
```
workitems_design_element = project.searchWorkitem('type:task', field_list=['id', 'author', 'customFields.int_field', 'customFields.string_field'])

Just replace 'int_field' and 'string_field' with your custom field names.

Let me know if this works for you.

Jesper

**Comment by nickdante8** [comment]
ye

> Hi,
> 
> You are very close, you specify the custom field(s) like so:
> 
> ```
> workitems_design_element = project.searchWorkitem('type:task', field_list=['id', 'author', 'customFields.int_field', 'customFields.string_field'])
> ```
> 
> Just replace 'int_field' and 'string_field' with your custom field names.
> 
> Let me know if this works for you.
> 
> Jesper

**Comment by jesper-raemaekers** [comment]
Hi,

The documentation is mainly build around my use cases, but i will add this (and other questions) tot he documentation.

Jesper
