### ISSUE TITLE
Access ConvertToPlainText()

### ISSUE THREAD

**Issue by krishtej23** [jesper-raemaekers/python-polarion#54]
Hi, I am trying to convert html version of work item description to plain text. Can this function be available in the api?
[https://almdemo.polarion.com/polarion/sdk/doc/javadoc/com/polarion/core/util/types/Text.html#convertToPlainText()](https://almdemo.polarion.com/polarion/sdk/doc/javadoc/com/polarion/core/util/types/Text.html#convertToPlainText()). This saves a lot of work in cleaning up the html content.
Thanks in advance.

**Comment by jesper-raemaekers** [comment]
Good idea, i think it will be a help full function to have available.

**Comment by krishtej23** [comment]
Just curious, any update on this?

**Comment by jesper-raemaekers** [comment]
I created a simple function. You can try it to see if it works for you.
You can expect it to be released together with issue #56

**Comment by krishtej23** [comment]
I already used regex expressions to clean up the work items. For requirements having references workitems as shown below, the reference items will be lost. Example: below requirement will be cleaned up.
```
Server shall<br/>
<ul>
  <li> Update <span class="polarion-rte-link" data-type="workItem" id="fake" data-item-id="ABC-1234" data-option-id="long"></span> to 0%</li>
</ul>
when 
<ul>
  <li> <span class="polarion-rte-link" data-type="workItem" id="fake" data-item-id="XYZ-123" data-option-id="long"></span> is configured to 1: Enable AND </li>
  <li><span class="polarion-rte-link" data-type="workItem" id="fake" data-item-id="ABC-456" data-option-id="long"></span> or <span class="polarion-rte-link" data-type="workItem" id="fake" data-item-id="XYZ-456" data-option-id="long"></span> is Active AND</li>
  <li> <span class="polarion-rte-link" data-type="workItem" id="fake" data-item-id="ABC-14321" data-option-id="long"></span>  is Active<br/>
    </li>
</ul>
```
as
```
Server shall

   Update  to 0%

when 

    is configured to 1: Enable AND 
   or  is Active AND
     is Active
```
but I need as
```
Server shall

   Update ABC-1234 to Empty (0%)

when 

   XYZ-123 is configured to 1: Enable AND 
   ABC-456 or XYZ-456 is Active AND
   ABC-14321 is Active
```

Is there a reason why we cannot access ConvertToPlainText()?

**Comment by jesper-raemaekers** [comment]
Yes, because it is a function only available in the java API and not in the WSDL API. If you navigate to http://<your domain>/polarion/ws/services you will find a list with all functions that are available. This is limited to functions interfacing directly to polarion, which ConvertToPlainText does not do unfortunately.

**Comment by jesper-raemaekers** [comment]
I've now created a HTML parser. This should handle your links correctly. I do foresee some other formatting issues when, for example, tables are in the description.

**Comment by jesper-raemaekers** [comment]
I think the current solution is a decent one. Let me know if you tested it and whether it works for your needs.

**Comment by krishtej23** [comment]
Thanks. Still did not get time to test this functionality. Sorry. Will test and update the results when I can.
