### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by maiducduy** [jesper-raemaekers/python-polarion#67]
I think it could be great if we could provide proxy information while creating an instance of Polarion as optional info.

**Comment by jesper-raemaekers** [comment]
Are you able to test with a proxy?
If so, please take the code from the commit in this reference and try and use it like so:

```
pol = polarion.Polarion('http://<domain>/polarion', 'user', 'pw', proxy='ip:port')
```

**Comment by kschmiechen** [comment]
I'm not sure if this is also relevant for python, but to use proxies, the following fix needed to be implemented for the java client: https://issues.apache.org/jira/browse/AXIS-1356

**Comment by maiducduy** [comment]
> 

It works well with proxy.

**Comment by jesper-raemaekers** [comment]
> I'm not sure if this is also relevant for python, but to use proxies, the following fix needed to be implemented for the java client: https://issues.apache.org/jira/browse/AXIS-1356

Thank you for noticing and providing feedback. I do think this will not be an issue because it looks like a change inside the java library itself.

**Comment by jesper-raemaekers** [comment]
this has been merged and will be published in the next release
