### ISSUE TITLE
Create multiple workitems in a document without creating many document revisions

### ISSUE THREAD

**Issue by sedlacekdavid** [jesper-raemaekers/python-polarion#83]
Hi, 
is it possible?

I can successfully create a new document with many workitems, everything is working fine, but I have big issues with creating thousands of document revisions. Each one per a new workitem I create.

I found some references to "sessions" and transactions, but I didn't manage to get it working.

Thank you and keep it up!

**Comment by jesper-raemaekers** [comment]
I probably tried the same as you (see the new branch_ but i also have no luck with this feature.
When i begin a transaction and then check if it exists, i get a False....
Not sure where to go from here though.

**Comment by sedlacekdavid** [comment]
Yes this is the API I'd like to use. Don't know either - so in case you don't know, then not sure if there will be someone else to help.

I seen some code running directly in Polarion documents - macros? They were using very similar tracker interface to the tracker-style - and on top of that there was this session service I'm trying to use it and it was working.

## $transactionService.beginTx()
## $transactionService.commitTx()

The reason I'm mentioning this is that it must be usable somehow - but not sure what can be done on your Polarion API side....

**Comment by sedlacekdavid** [comment]
Another example:
`<html><body>


#set ($titleWorkItem = $allWorkItems.get(0))
--
  | 107 | #set ($docTitle = $docChosen.getTitleOrName())
  | 108 | #if ($titleWorkItem.getTitle() != $docTitle)
  | 109 | ## start transaction
  | 110 | ##         $transactionService.beginTx()
  | 111 | ## set first heading in document (title)
  | 112 | $titleWorkItem.setTitle($docTitle)
  | 113 | $titleWorkItem.save()
  | 114 | ## set document title
  | 115 | $docChosen.setTitle($docTitle)
  | 116 | ##         $docChosen.save()
  | 117 | ## end transaction
  | 118 | ##         $transactionService.commitTx()
  | 119 | #end


</body>
</html>`

**Comment by jesper-raemaekers** [comment]
Could you maybe check the output of [txExists](https://almdemo.polarion.com/polarion/sdk/doc/javadoc/com/polarion/platform/ITransactionService.html#txExists())? Just to help understand that this should in fact return true after beginTx?

**Comment by fuchse-ego** [comment]
This answer at SO seems related: https://stackoverflow.com/a/78618481
Someone claimed to get the transaction service to work.

**Comment by fuchse-ego** [comment]
Hi  @jesper-raemaekers ,

is it possible to reopen this issue or would it be better to open a new one?
