### ISSUE TITLE
addLinkedItem does not create the corresponding mirror of "role"

### ISSUE THREAD

**Issue by rikardhodzic** [jesper-raemaekers/python-polarion#87]
addLinkedItem does not create the corresponding mirror of role.

workitem_1.addLinkedItem(workitem_2, role = 'refers to') will not create a link in workitem_2 with role "is refered by" to workitem_1.
Instead, workitem_2 will have a link back to workitem_1 with role "refers to" which is not intended.

The link itself seems intact, the link create for workitem_1 is pointing to workitem_2 i.e you cannot remove/edit the link from workitem_2 but only from workitem_1.

tested in python version 3.9.7
polarion version 1.0.0

**Comment by jesper-raemaekers** [comment]
Thanks for the update
