### ISSUE TITLE
Workitem.addHyperlink() requires an ENUM for the hyperlink_type

### ISSUE THREAD

**Issue by wbrenneman** [jesper-raemaekers/python-polarion#91]
Since the hyperlink_type ids can be configurable and might not match the HyperlinkRoles enum values, it would be better to allow a direct str input to allow users to provide a custom value needed for their project

Something like this:
```
def addHyperlink(self, url, hyperlink_type: HyperlinkRoles):
    """
    Adds a hyperlink to the workitem.

    :param url: The URL to add
    :param hyperlink_type: Select internal or external hyperlink
    """
    service = self._polarion.getService('Tracker')
    if isinstance(hyperlink_type, Enum):   #convert Enum to str
        hyperlink_type = hyperlink_type.value  
    service.addHyperlink(self.uri, url, {'id': hyperlink_type})
    self._reloadFromPolarion()
```

Currently for my implementation I have to create a Custom Enum and pass that into the addHyperlink()

**Comment by jesper-raemaekers** [comment]
I wasn't even aware that the link types could be custom. I have taken your suggestion, it now accepts both the enum and a string.

**Comment by wbrenneman** [comment]
Yes, I think technically 'everything' for a project could be configured. I don't think there are really any reasons to change them, but possibly add.  I am guessing the difference could be based on when each of our polarion servers were setup.
