### ISSUE TITLE
Is it possible to do global query testrecord or list projects and testruns?

### ISSUE THREAD

**Issue by smithlai** [jesper-raemaekers/python-polarion#94]
Would you mind giving me a hand?
I want to list all testrecords with the same workitem id.
I can only access single testrecord by polarion.getProject("aaaaa").getTestrun("bbbbb").getTestcase("ccccc").

Is there anyway to review all testrecords ("ccccc") among all testruns and projects?

**Comment by jesper-raemaekers** [comment]
Excellent question. I looked for a bit but i could not figure out how to do in in the Polarion user interface So I'm unsure how it would work.
If you could provide an example query that works in polarion i can have a try.

**Comment by smithlai** [comment]
As the document describes, polarion disabled the function deliberately.  
[searchTestRecords](https://almdemo.polarion.com/polarion/sdk/doc/javadoc/com/polarion/alm/tracker/ITestManagementService.html#searchTestRecords(java.lang.String,java.lang.String,int))

My approach is to dump all data to local for me to search.
```python
pol = polarion.Polarion(url, name, pass)
service = pol.getService('Project')
root = service.getRootProjectGroup()
all_projects = service.getDeepContainedProjects(root.uri)
for pk in all_projects
     testruns = pol.searchTestRuns(f"", pk)  #modified from Project.searchTestRuns()
     ...........
     .............
```

**Comment by jesper-raemaekers** [comment]
From what i can see and do i find no better way to do this since that function was disabled.
