### ISSUE TITLE
Do you have idea about SetLinkedResource?

### ISSUE THREAD

**Issue by man8989** [jesper-raemaekers/python-polarion#95]
Hello
I'm using your package well.
Due to company policy, resource traceability cannot be set.
I cannot connect git server directly.(Administration -> Repositories -> Configuration, Resource Traceability)

I want to input LinkedResource data manually using wsdl.
I know there is no function setLinkedResource in wsdl.
Do you have idea to update linkedresource data?

![image](https://user-images.githubusercontent.com/25956780/202460005-9e53d2c1-f215-45ba-b2da-d2a06c95c4a9.png)

**Comment by man8989** [comment]
I've added LinkedResourceType in polarion.py

**in polarion.py**
![image](https://user-images.githubusercontent.com/25956780/202470848-54a787ae-0185-45f0-a33e-28cdde120b7c.png)

![image](https://user-images.githubusercontent.com/25956780/202470731-a39e821d-0771-4e6c-a3ce-09eb047c2d53.png)

**Comment by jesper-raemaekers** [comment]
Okay I looked for this option but it seems it is not available. Most options present themselves in the workitem object and can be edited that way, this is not the case for linked resources.
